### ISSUE TITLE
review

### ISSUE THREAD

**Issue by mahuntington** [aleongithub/aleongithub.github.io#2]
Zdravo!!

Nice work, despite it not working.  The javascript is solid, so that counts for a lot.  Here are some thoughts:
1. Separate your js/css into separate directories.  This might seem silly now, but once you get into a production environment, it really helps keep things organized.
2. Good work on formatting.  Believe it or not, many people can't keep their code indented correctly, and it really makes it difficult to debug.  The indentation really gives the code structure.  Keep it up!
3. I liked that you tackled canvas (even if it failed), but if I was doing this, I would probably use divs.  It's surprising, what you can do with basic html elements, without needing to resort to canvas.
4. Your code was logically written, laid out, well named named.  This is really REALLY important, so keep this in mind when going forward.  So far so good... don't let it slide :)
5.  Along the same lines, you commented quite well.  I usually suggest putting in a comment for every action that takes place in your code.  In production, this will let other devs (and your future self) know what you were thinking when you wrote the code.
6.  Make it responsive!! Your game should work for all screen sizes.  This wasn't a requirement for the project, but something that you should always strive for.

If you have any questions about something that you couldn't figure out, feel free to hit me up, and we can chat about it.

**Comment by aleongithub** [comment]
Hvala for the nice feedback!
